### ISSUE TITLE
datePublished & dateModified props - why nulls?

### ISSUE THREAD

**Issue by rwasiak** [spences10/react-seo-component#86] opened 2020-06-15 20:52 UTC
Hello 👋

great component! 

I've found one interesting thing.

https://github.com/spences10/react-seo-component/blob/d534b8c3773d7ff81ee0114a4aa8daa3e3f5617a/src/seo.tsx#L40-L45

Why there is a null replacement when datePublished or dateModified is provided? Is there any reason for SEO or it is just an oversight?

**Comment by spences10** [comment] 2020-06-16 11:44
Hey @rwasiak, yeah that's my mistake!

Feel free to submit a PR to correct or I can amend myself.

Thanks :pray:

**Comment by spences10** [comment] 2020-06-19 07:15
Hey @rwasiak I've just tested this and it works as intended.

The logic is, if there's no date being passed to the component then it will substitute with the current date time.

Closing now, feel free to reopen with any suggestions you think would improve this.

Thanks.

**Closed as completed by spences10** 2020-06-19 07:15 UTC

**Comment by rwasiak** [comment] 2020-06-20 13:43
Hey @spences10 - it is intended that for passing publishedDate or modifiedDate to SEO component you receive nulls? 

Please look at this PR https://github.com/spences10/react-seo-component/pull/87

PS - I can't reopen issue closed by someone else 😄
